mutation Comment($content: String!, $projectId: String!) {
	comment(content: $content, projectId: $projectId) {
		id
		content
		createdAt
	}
}

query GetComments {
	getComments {
		id
		content
		createdAt
		updatedAt
	}
}

mutation DeleteComment($commentId: String!) {
	deleteComment(commentId: $commentId)
}

mutation UpdateComment($newContent: String!, $commentId: String!) {
	updateComment(newContent: $newContent, commentId: $commentId)
}
