mutation Comment($content: String!, $projectId: String!) {
	comment(content: $content, projectId: $projectId) {
		id
		content
		createdAt
	}
}

mutation DeleteComment($commentId: String!) {
	deleteComment(commentId: $commentId)
}
