query GetLanguages {
	getLanguages {
		id
		name
	}
}

mutation DeleteLanguage($deleteLanguageId: String!) {
	deleteLanguage(id: $deleteLanguageId)
}

mutation CreateLanguage($data: LanguageInput!) {
	createLanguage(data: $data) {
		id
		name
	}
}
