mutation CreateProject($data: NewProjectInput!) {
	createProject(data: $data) {
		title
		user {
			pseudo
			role
			id
			email
		}
		id
		isPublic
	}
}

query GetMyProjects {
	getMyProjects {
		title
		isPublic
		createdAt
		updatedAt
		user {
			pseudo
			role
			id
			email
		}
		id
	}
}

query GetProjectById($getProjectId: String!) {
	getProject(id: $getProjectId) {
		id
		title
		isPublic
		codes {
			content
			language {
				name
				id
			}
		}
	}
}

query GetPublicsProjects($limit: Float!, $offset: Float!) {
	getPublicsProjects(limit: $limit, offset: $offset) {
		isPublic
		updatedAt
		title
		user {
			pseudo
			id
		}
		createdAt
		id
	}
}
