mutation CreateProject($data: NewProjectInput!) {
	createProject(data: $data) {
		title
		user {
			pseudo
			role
			id
			email
		}
		id
		isPublic
	}
}

query GetProjectById($getProjectId: String!) {
	getProject(id: $getProjectId) {
		id
		title
		isPublic
		codes {
			id
			content
			language {
				name
				id
			}
		}
	}
}

query GetPaginateProjects(
	$withUserProject: Boolean!
	$isUser: Boolean!
	$searchUser: String!
	$searchProject: String!
	$offset: Float!
	$limit: Float!
) {
	getPaginateProjects(
		withUserProject: $withUserProject
		isUser: $isUser
		searchUser: $searchUser
		searchProject: $searchProject
		offset: $offset
		limit: $limit
	) {
		hasMore
		isUserSearch
		projects {
			id
			isPublic
			title
			createdAt
			user {
				pseudo
			}
		}
	}
}
