mutation CreateProject($data: NewProjectInput!) {
	createProject(data: $data) {
		title
		user {
			pseudo
			role
			id
			email
		}
		id
		isPublic
	}
}

query GetMyProjects($limit: Float!, $offset: Float!) {
	getMyProjects(limit: $limit, offset: $offset) {
		projects {
			id
			isPublic
			title
			createdAt
			user {
				pseudo
			}
		}
		hasMore
	}
}

query GetProjectById($getProjectId: String!) {
	getProject(id: $getProjectId) {
		id
		title
		isPublic
		codes {
			id
			content
			language {
				name
				id
			}
		}
		user {
			id
			pseudo
		}
		likes {
			id
			user {
				id
				pseudo
			}
		}
	}
}

query GetPublicsProjects($offset: Float!, $limit: Float!) {
	getPublicsProjects(offset: $offset, limit: $limit) {
		projects {
			id
			isPublic
			title
			createdAt
			user {
				pseudo
			}
		}
		hasMore
	}
}
