mutation CreateReporting($data: NewReportInput!) {
	createReporting(data: $data) {
		id
	}
}

query GetAllReports {
	getAllReports {
		id
		content
		project {
			id
		}
		reportings {
			id
		}
	}
}

mutation DeleteCommentAndLinkedReport(
	$deleteCommentAndLinkedReportId: String!
) {
	deleteCommentAndLinkedReport(id: $deleteCommentAndLinkedReportId)
}
