query Users {
	users {
		id
		role
		email
		pseudo
		executionCounter
		isPremium
	}
}

query GetExecutionCounter {
	getExecutionCounter {
		executionCounter
		isPremium
	}
}

mutation SignUp($data: NewUserInput!) {
	createUser(data: $data) {
		email
		id
		pseudo
		role
		executionCounter
		isPremium
	}
}

mutation SignIn($data: SigninInput!) {
	signin(data: $data)
}

mutation Logout {
	logout
}

mutation DeleteUser($deleteUserId: String!, $inAdminPanel: Boolean!) {
	deleteUser(id: $deleteUserId, inAdminPanel: $inAdminPanel)
}

query GetUserProfile {
	getUserProfile {
		id
		role
		email
		pseudo
		executionCounter
		isPremium
	}
}

mutation IncrementExecutionCounter($counter: ExecutionCounterInput!) {
	incrementExecutionCounter(counter: $counter)
}

mutation UpdateUserIsPremium($isPremium: Boolean!) {
	updateUserIsPremium(isPremium: $isPremium)
}

mutation UpdateUsername($datas: UpdateUsernameInput!) {
	updateUsername(datas: $datas)
}

mutation UpdateUserPassword($datas: UpdatePasswordInput!) {
	updateUserPassword(datas: $datas)
}
