query Users {
	users {
		email
		id
	}
}

query GetExecutionCounter {
	getExecutionCounter {
		executionCounter
		isPremium
	}
}

mutation SignUp($data: NewUserInput!) {
	createUser(data: $data) {
		email
		id
		pseudo
		role
	}
}

mutation SignIn($data: SigninInput!) {
	signin(data: $data)
}

mutation Logout {
	logout
}

query GetUserProfile {
	getUserProfile {
		email
		id
		pseudo
		role
	}
}

mutation IncrementExecutionCounter($counter: ExecutionCounterInput!) {
	incrementExecutionCounter(counter: $counter)
}
