services:
  db:
    image: postgres:15-alpine
    stop_grace_period: 0s
    environment:
      POSTGRES_PASSWORD: ${DB_PASS-postgres}
      PGUSER: ${DB_USER-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - prodDB:/var/lib/postgresql/data

  backend:
    platform: linux/x86_64
    stop_grace_period: 0s
    env_file: backend/.env
    environment:
      DB_HOST: db
      DB_PASS: ${DB_PASS-postgres}
      DB_USER: ${DB_USER-postgres}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY:-default}
      NODE_ENV: ${NODE_ENV:-production}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-default}
    depends_on:
      db:
        condition: service_healthy
    image: fond2laclasse/wild-code-online-backend:latest

  frontend:
    platform: linux/x86_64
    environment:
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:-default}
      - NEXT_PUBLIC_MODE=production
    stop_grace_period: 0s
    env_file: frontend/.env
    image: fond2laclasse/wild-code-online-frontend:latest

  gateway:
    restart: always
    stop_grace_period: 0s
    build:
      context: gateway
      dockerfile: Dockerfile.production
    ports:
      - ${GATEWAY_PORT-80}:80

volumes:
  prodDB:
