name: "deploy-prod"

on:
  workflow_dispatch:

jobs:
  call-test-front:
    uses: WildCodeSchool/2023-11-wns-bleu-g1/.github/workflows/test-front.yml@master

  call-test-back:
    uses: WildCodeSchool/2023-11-wns-bleu-g1/.github/workflows/test-back.yml@master

  build-and-push-frontend-production:
    needs: call-test-front
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          file: "Dockerfile.production"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wild-code-online-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-backend-production:
    needs: call-test-back
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:backend"
          file: "Dockerfile.production"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wild-code-online-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
