#name: "test-front"
#
#on:
#  pull_request:
#  workflow_call:
#
#
#jobs:
#  test-client:
#    runs-on: ubuntu-latest
#    if: ${{ github.event_name == 'pull_request' }}
#    defaults:
#      run:
#        working-directory: ./frontend
#    steps:
#      - name: Get the code
#        uses: actions/checkout@v4
#      - name: Install nodeJS
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#      - name: Install deps
#        run: npm ci
#      - name: Run tests
#        run: npm test
#  build-and-push-frontend:
#    runs-on: ubuntu-latest
#    if: ${{ github.event_name == 'workflow_call' }}
#    steps:
#      - name: Set up Qemu
#        uses: docker/setup-qemu-action@v3
