name: "test-front"

on:
  pull_request:
    paths:
      - "frontend/**"
  workflow_call:

jobs:
  linting-frontend:
    name: Linting frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Code Linting
        run: npm run lint

  prettier-frontend:
    name: Prettier frontend
    needs: [linting-frontend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Code Prettier
        run: npx prettier . --check

  frontend-integration-tests:
    name: integration tests
    needs: prettier-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  frontend-e2e-tests:
    name: e2e tests
    runs-on: ubuntu-latest
#    needs: frontend-integration-tests
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - name: Install root dependencies
        run: npm ci
      - name: Start server in the background
        run: npm run dev &
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
